export enum CHAIN_ID {
  ETHEREUM = "1",
  UBIQ = "8",
  OPTIMISM = "10",
  FLARE = "14",
  SONGBIRD = "19",
  ELASTOS = "20",
  KARDIA = "24",
  CRONOS = "25",
  RSK = "30",
  TELOS = "40",
  LUKSO = "42",
  CRAB = "44",
  DARWINIA = "46",
  XDC = "50",
  CSC = "52",
  ZYX = "55",
  BINANCE = "56",
  BINANCE_TESTNET = "97",
  SYSCOIN = "57",
  GOCHAIN = "60",
  ETHEREUMCLASSIC = "61",
  OKEXCHAIN = "66",
  HOO = "70",
  METER = "82",
  NOVA_NETWORK = "87",
  TOMOCHAIN = "88",
  BITKUB = "96",
  XDAI = "100",
  VELAS = "106",
  THUNDERCORE = "108",
  ENULS = "119",
  FUSE = "122",
  HECO = "128",
  UNICHAIN = "130",
  POLYGON = "137",
  SONIC = "146",
  SHIMMER_EVM = "148",
  RBN = "151",
  OMNI = "166",
  MANTA = "169",
  HSK = "177",
  WATER = "181",
  XLAYER = "196",
  XDAIARB = "200",
  OP_BNB = "204",
  VINUCHAIN = "207",
  ENERGYWEB = "246",
  OASYS = "248",
  FANTOM = "250",
  FRAXTAL = "252",
  HPB = "269",
  BOBA = "288",
  OMAX = "311",
  FILECOIN = "314",
  KUCOIN = "321",
  ZKSYNC_ERA = "324",
  SHIDEN = "336",
  THETA = "361",
  PULSE = "369",
  CRONOS_ZKEVM = "388",
  SX = "416",
  AREON = "463",
  WC = "480",
  CANDLE = "534",
  ROLLUX = "570",
  ASTAR = "592",
  REDSTONE = "690",
  MATCHAIN = "698",
  CALLISTO = "820",
  TARA = "841",
  WANCHAIN = "888",
  LYRA_CHAIN = "957",
  BIFROST = "996",
  CONFLUX = "1030",
  METIS = "1088",
  DYMENSION = "1100",
  POLYGON_ZKEVM = "1101",
  CORE = "1116",
  LISK = "1135",
  ULTRON = "1231",
  STEP = "1234",
  MOONBEAM = "1284",
  MOONRIVER = "1285",
  SEI = "1329",
  LIVING_ASSETS_MAINNET = "1440",
  STY = "1514",
  TENET = "1559",
  GRAVITY = "1625",
  REYA_NETWORK = "1729",
  SONEIUM = "1868",
  SWELLCHAIN = "1923",
  ONUS = "1975",
  HUBBLENET = "1992",
  SANKO = "1996",
  DOGECHAIN = "2000",
  MILKOMEDA = "2001",
  MILKOMEDA_A1 = "2002",
  KAVA = "2222",
  SOMA = "2332",
  KARAK = "2410",
  ABSTRACT = "2741",
  ABSTRACT_TESTNET = "11124",
  MORPH = "2818",
  CROSSFI = "4158",
  BEAM = "4337",
  IOTEX = "4689",
  MANTLE = "5000",
  XLC = "5050",
  NAHMII = "5551",
  BOUNCEBIT = "6001",
  TOMBCHAIN = "6969",
  ZETACHAIN = "7000",
  PLANQ = "7070",
  BITROCK = "7171",
  XSAT = "7200",
  CYETH = "7560",
  CANTO = "7700",
  KLAYTN = "8217",
  THAT = "8428",
  BASE = "8453",
  HELA = "8668",
  IOTAEVM = "8822",
  JBC = "8899",
  EVMOS = "9001",
  CARBON = "9790",
  SMARTBCH = "10000",
  ARTELA = "11820",
  IMMUTABLE_ZKEVM = "13371",
  LOOP = "15551",
  GENESYS = "16507",
  EOS_EVM = "17777",
  MAP_PROTOCOL = "22776",
  SAPPHIRE = "23294",
  BITGERT = "32520",
  FUSION = "32659",
  ZILLIQA = "32769",
  APECHAIN = "33139",
  EDU_CHAIN = "41923",
  ARBITRUM = "42161",
  ARBITRUM_TESTNET_GOERLI = "421613",
  ARBITRUM_TESTNET_SEPOLIA = "421614",
  ARBITRUM_NOVA = "42170",
  CELO = "42220",
  OASIS = "42262",
  ASSETCHAIN = "42420",
  ETHERLINK = "42793",
  AVALANCHE = "43114",
  REI = "47805",
  ZIRCUIT = "48900",
  SOPHON = "50104",
  ETN = "52014",
  SUPERPOSITION = "55244",
  REICHAIN = "55555",
  BOBA_BNB = "56288",
  INK = "57073",
  LINEA = "59144",
  BOB = "60808",
  GODWOKEN = "71402",
  BERACHAIN = "80094",
  BLAST = "81457",
  CHILIZ = "88888",
  STRATIS = "105105",
  REAL = "111188",
  ODYSSEY = "153153",
  TAIKO = "167000",
  BITLAYER = "200901",
  HYDRATION = "222222",
  PAREX = "322202",
  POLIS = "333999",
  KEKCHAIN = "420420",
  SCROLL = "534352",
  ZERO_NETWORK = "543210",
  ZKLINK_NOVA = "810180",
  VISION = "888888",
  SAAKURU = "7225878",
  ZORA = "7777777",
  CORN = "21000000",
  NEON = "245022934",
  LUMIA = "994873017",
  AURORA = "1313161554",
  HARMONY = "1666600000",
  PALM = "11297108109",
  ZENIQ = "383414847825",
  CURIO = "836542336838601",
  MODE = "34443",
  SOLANA = "900900900",
  SOLANA_TESTNET = "901901901",
  SOLANA_DEVNET = "902902902",
}

export const chains = [
  CHAIN_ID.ETHEREUM,
  CHAIN_ID.UBIQ,
  CHAIN_ID.OPTIMISM,
  CHAIN_ID.FLARE,
  CHAIN_ID.SONGBIRD,
  CHAIN_ID.ELASTOS,
  CHAIN_ID.KARDIA,
  CHAIN_ID.CRONOS,
  CHAIN_ID.RSK,
  CHAIN_ID.TELOS,
  CHAIN_ID.LUKSO,
  CHAIN_ID.CRAB,
  CHAIN_ID.DARWINIA,
  CHAIN_ID.XDC,
  CHAIN_ID.CSC,
  CHAIN_ID.ZYX,
  CHAIN_ID.BINANCE,
  CHAIN_ID.SYSCOIN,
  CHAIN_ID.GOCHAIN,
  CHAIN_ID.ETHEREUMCLASSIC,
  CHAIN_ID.OKEXCHAIN,
  CHAIN_ID.HOO,
  CHAIN_ID.METER,
  CHAIN_ID.NOVA_NETWORK,
  CHAIN_ID.TOMOCHAIN,
  CHAIN_ID.BITKUB,
  CHAIN_ID.XDAI,
  CHAIN_ID.SOLANA,
  CHAIN_ID.VELAS,
  CHAIN_ID.THUNDERCORE,
  CHAIN_ID.ENULS,
  CHAIN_ID.FUSE,
  CHAIN_ID.HECO,
  CHAIN_ID.UNICHAIN,
  CHAIN_ID.POLYGON,
  CHAIN_ID.SONIC,
  CHAIN_ID.SHIMMER_EVM,
  CHAIN_ID.RBN,
  CHAIN_ID.OMNI,
  CHAIN_ID.MANTA,
  CHAIN_ID.HSK,
  CHAIN_ID.WATER,
  CHAIN_ID.XLAYER,
  CHAIN_ID.XDAIARB,
  CHAIN_ID.OP_BNB,
  CHAIN_ID.VINUCHAIN,
  CHAIN_ID.ENERGYWEB,
  CHAIN_ID.OASYS,
  CHAIN_ID.FANTOM,
  CHAIN_ID.FRAXTAL,
  CHAIN_ID.HPB,
  CHAIN_ID.BOBA,
  CHAIN_ID.OMAX,
  CHAIN_ID.FILECOIN,
  CHAIN_ID.KUCOIN,
  CHAIN_ID.ZKSYNC_ERA,
  CHAIN_ID.SHIDEN,
  CHAIN_ID.THETA,
  CHAIN_ID.PULSE,
  CHAIN_ID.CRONOS_ZKEVM,
  CHAIN_ID.SX,
  CHAIN_ID.AREON,
  CHAIN_ID.WC,
  CHAIN_ID.CANDLE,
  CHAIN_ID.ROLLUX,
  CHAIN_ID.ASTAR,
  CHAIN_ID.REDSTONE,
  CHAIN_ID.MATCHAIN,
  CHAIN_ID.CALLISTO,
  CHAIN_ID.TARA,
  CHAIN_ID.WANCHAIN,
  CHAIN_ID.LYRA_CHAIN,
  CHAIN_ID.BIFROST,
  CHAIN_ID.CONFLUX,
  CHAIN_ID.METIS,
  CHAIN_ID.DYMENSION,
  CHAIN_ID.POLYGON_ZKEVM,
  CHAIN_ID.CORE,
  CHAIN_ID.LISK,
  CHAIN_ID.ULTRON,
  CHAIN_ID.STEP,
  CHAIN_ID.MOONBEAM,
  CHAIN_ID.MOONRIVER,
  CHAIN_ID.SEI,
  CHAIN_ID.LIVING_ASSETS_MAINNET,
  CHAIN_ID.STY,
  CHAIN_ID.TENET,
  CHAIN_ID.GRAVITY,
  CHAIN_ID.REYA_NETWORK,
  CHAIN_ID.SONEIUM,
  CHAIN_ID.SWELLCHAIN,
  CHAIN_ID.ONUS,
  CHAIN_ID.HUBBLENET,
  CHAIN_ID.SANKO,
  CHAIN_ID.DOGECHAIN,
  CHAIN_ID.MILKOMEDA,
  CHAIN_ID.MILKOMEDA_A1,
  CHAIN_ID.KAVA,
  CHAIN_ID.SOMA,
  CHAIN_ID.KARAK,
  CHAIN_ID.ABSTRACT,
  CHAIN_ID.MORPH,
  CHAIN_ID.CROSSFI,
  CHAIN_ID.BEAM,
  CHAIN_ID.IOTEX,
  CHAIN_ID.MANTLE,
  CHAIN_ID.XLC,
  CHAIN_ID.NAHMII,
  CHAIN_ID.BOUNCEBIT,
  CHAIN_ID.TOMBCHAIN,
  CHAIN_ID.ZETACHAIN,
  CHAIN_ID.PLANQ,
  CHAIN_ID.BITROCK,
  CHAIN_ID.XSAT,
  CHAIN_ID.CYETH,
  CHAIN_ID.CANTO,
  CHAIN_ID.KLAYTN,
  CHAIN_ID.THAT,
  CHAIN_ID.BASE,
  CHAIN_ID.HELA,
  CHAIN_ID.IOTAEVM,
  CHAIN_ID.JBC,
  CHAIN_ID.EVMOS,
  CHAIN_ID.CARBON,
  CHAIN_ID.SMARTBCH,
  CHAIN_ID.ARTELA,
  CHAIN_ID.IMMUTABLE_ZKEVM,
  CHAIN_ID.LOOP,
  CHAIN_ID.GENESYS,
  CHAIN_ID.EOS_EVM,
  CHAIN_ID.MAP_PROTOCOL,
  CHAIN_ID.SAPPHIRE,
  CHAIN_ID.BITGERT,
  CHAIN_ID.FUSION,
  CHAIN_ID.ZILLIQA,
  CHAIN_ID.APECHAIN,
  CHAIN_ID.EDU_CHAIN,
  CHAIN_ID.ARBITRUM,
  CHAIN_ID.ARBITRUM_NOVA,
  CHAIN_ID.CELO,
  CHAIN_ID.OASIS,
  CHAIN_ID.ASSETCHAIN,
  CHAIN_ID.ETHERLINK,
  CHAIN_ID.AVALANCHE,
  CHAIN_ID.REI,
  CHAIN_ID.ZIRCUIT,
  CHAIN_ID.SOPHON,
  CHAIN_ID.ETN,
  CHAIN_ID.SUPERPOSITION,
  CHAIN_ID.REICHAIN,
  CHAIN_ID.BOBA_BNB,
  CHAIN_ID.INK,
  CHAIN_ID.LINEA,
  CHAIN_ID.BOB,
  CHAIN_ID.GODWOKEN,
  CHAIN_ID.BERACHAIN,
  CHAIN_ID.BLAST,
  CHAIN_ID.CHILIZ,
  CHAIN_ID.STRATIS,
  CHAIN_ID.REAL,
  CHAIN_ID.ODYSSEY,
  CHAIN_ID.TAIKO,
  CHAIN_ID.BITLAYER,
  CHAIN_ID.HYDRATION,
  CHAIN_ID.PAREX,
  CHAIN_ID.POLIS,
  CHAIN_ID.KEKCHAIN,
  CHAIN_ID.SCROLL,
  CHAIN_ID.ZERO_NETWORK,
  CHAIN_ID.ZKLINK_NOVA,
  CHAIN_ID.VISION,
  CHAIN_ID.SAAKURU,
  CHAIN_ID.ZORA,
  CHAIN_ID.CORN,
  CHAIN_ID.NEON,
  CHAIN_ID.LUMIA,
  CHAIN_ID.AURORA,
  CHAIN_ID.HARMONY,
  CHAIN_ID.PALM,
  CHAIN_ID.ZENIQ,
  CHAIN_ID.CURIO,
  CHAIN_ID.MODE,
];

export const chainSlugs: Partial<Record<CHAIN_ID, string>> = {
  [CHAIN_ID.ETHEREUM]: "ethereum",
  [CHAIN_ID.UBIQ]: "ubiq",
  [CHAIN_ID.OPTIMISM]: "optimism",
  [CHAIN_ID.FLARE]: "flare",
  [CHAIN_ID.SONGBIRD]: "songbird",
  [CHAIN_ID.ELASTOS]: "elastos",
  [CHAIN_ID.KARDIA]: "kardia",
  [CHAIN_ID.CRONOS]: "cronos",
  [CHAIN_ID.RSK]: "rsk",
  [CHAIN_ID.TELOS]: "telos",
  [CHAIN_ID.LUKSO]: "lukso",
  [CHAIN_ID.CRAB]: "crab",
  [CHAIN_ID.DARWINIA]: "darwinia",
  [CHAIN_ID.XDC]: "xdc",
  [CHAIN_ID.CSC]: "csc",
  [CHAIN_ID.ZYX]: "zyx",
  [CHAIN_ID.BINANCE]: "binance",
  [CHAIN_ID.SYSCOIN]: "syscoin",
  [CHAIN_ID.GOCHAIN]: "gochain",
  [CHAIN_ID.ETHEREUMCLASSIC]: "ethereumclassic",
  [CHAIN_ID.OKEXCHAIN]: "okexchain",
  [CHAIN_ID.HOO]: "hoo",
  [CHAIN_ID.METER]: "meter",
  [CHAIN_ID.NOVA_NETWORK]: "nova network",
  [CHAIN_ID.TOMOCHAIN]: "tomochain",
  [CHAIN_ID.BITKUB]: "bitkub",
  [CHAIN_ID.XDAI]: "xdai",
  [CHAIN_ID.SOLANA]: "solana",
  [CHAIN_ID.VELAS]: "velas",
  [CHAIN_ID.THUNDERCORE]: "thundercore",
  [CHAIN_ID.ENULS]: "enuls",
  [CHAIN_ID.FUSE]: "fuse",
  [CHAIN_ID.HECO]: "heco",
  [CHAIN_ID.UNICHAIN]: "unichain",
  [CHAIN_ID.POLYGON]: "polygon",
  [CHAIN_ID.SONIC]: "sonic",
  [CHAIN_ID.SHIMMER_EVM]: "shimmer_evm",
  [CHAIN_ID.RBN]: "rbn",
  [CHAIN_ID.OMNI]: "omni",
  [CHAIN_ID.MANTA]: "manta",
  [CHAIN_ID.HSK]: "hsk",
  [CHAIN_ID.WATER]: "water",
  [CHAIN_ID.XLAYER]: "xlayer",
  [CHAIN_ID.XDAIARB]: "xdaiarb",
  [CHAIN_ID.OP_BNB]: "op_bnb",
  [CHAIN_ID.VINUCHAIN]: "vinuchain",
  [CHAIN_ID.ENERGYWEB]: "energyweb",
  [CHAIN_ID.OASYS]: "oasys",
  [CHAIN_ID.FANTOM]: "fantom",
  [CHAIN_ID.FRAXTAL]: "fraxtal",
  [CHAIN_ID.HPB]: "hpb",
  [CHAIN_ID.BOBA]: "boba",
  [CHAIN_ID.OMAX]: "omax",
  [CHAIN_ID.FILECOIN]: "filecoin",
  [CHAIN_ID.KUCOIN]: "kucoin",
  [CHAIN_ID.ZKSYNC_ERA]: "zksync era",
  [CHAIN_ID.SHIDEN]: "shiden",
  [CHAIN_ID.THETA]: "theta",
  [CHAIN_ID.PULSE]: "pulse",
  [CHAIN_ID.CRONOS_ZKEVM]: "cronos zkevm",
  [CHAIN_ID.SX]: "sx",
  [CHAIN_ID.AREON]: "areon",
  [CHAIN_ID.WC]: "wc",
  [CHAIN_ID.CANDLE]: "candle",
  [CHAIN_ID.ROLLUX]: "rollux",
  [CHAIN_ID.ASTAR]: "astar",
  [CHAIN_ID.REDSTONE]: "redstone",
  [CHAIN_ID.MATCHAIN]: "matchain",
  [CHAIN_ID.CALLISTO]: "callisto",
  [CHAIN_ID.TARA]: "tara",
  [CHAIN_ID.WANCHAIN]: "wanchain",
  [CHAIN_ID.LYRA_CHAIN]: "lyra chain",
  [CHAIN_ID.BIFROST]: "bifrost",
  [CHAIN_ID.CONFLUX]: "conflux",
  [CHAIN_ID.METIS]: "metis",
  [CHAIN_ID.DYMENSION]: "dymension",
  [CHAIN_ID.POLYGON_ZKEVM]: "polygon zkevm",
  [CHAIN_ID.CORE]: "core",
  [CHAIN_ID.LISK]: "lisk",
  [CHAIN_ID.ULTRON]: "ultron",
  [CHAIN_ID.STEP]: "step",
  [CHAIN_ID.MOONBEAM]: "moonbeam",
  [CHAIN_ID.MOONRIVER]: "moonriver",
  [CHAIN_ID.SEI]: "sei",
  [CHAIN_ID.LIVING_ASSETS_MAINNET]: "living assets mainnet",
  [CHAIN_ID.STY]: "sty",
  [CHAIN_ID.TENET]: "tenet",
  [CHAIN_ID.GRAVITY]: "gravity",
  [CHAIN_ID.REYA_NETWORK]: "reya network",
  [CHAIN_ID.SONEIUM]: "soneium",
  [CHAIN_ID.SWELLCHAIN]: "swellchain",
  [CHAIN_ID.ONUS]: "onus",
  [CHAIN_ID.HUBBLENET]: "hubblenet",
  [CHAIN_ID.SANKO]: "sanko",
  [CHAIN_ID.DOGECHAIN]: "dogechain",
  [CHAIN_ID.MILKOMEDA]: "milkomeda",
  [CHAIN_ID.MILKOMEDA_A1]: "milkomeda_a1",
  [CHAIN_ID.KAVA]: "kava",
  [CHAIN_ID.SOMA]: "soma",
  [CHAIN_ID.KARAK]: "karak",
  [CHAIN_ID.ABSTRACT]: "abstract",
  [CHAIN_ID.MORPH]: "morph",
  [CHAIN_ID.CROSSFI]: "crossfi",
  [CHAIN_ID.BEAM]: "beam",
  [CHAIN_ID.IOTEX]: "iotex",
  [CHAIN_ID.MANTLE]: "mantle",
  [CHAIN_ID.XLC]: "xlc",
  [CHAIN_ID.NAHMII]: "nahmii",
  [CHAIN_ID.BOUNCEBIT]: "bouncebit",
  [CHAIN_ID.TOMBCHAIN]: "tombchain",
  [CHAIN_ID.ZETACHAIN]: "zetachain",
  [CHAIN_ID.PLANQ]: "planq",
  [CHAIN_ID.BITROCK]: "bitrock",
  [CHAIN_ID.XSAT]: "xsat",
  [CHAIN_ID.CYETH]: "cyeth",
  [CHAIN_ID.CANTO]: "canto",
  [CHAIN_ID.KLAYTN]: "klaytn",
  [CHAIN_ID.THAT]: "that",
  [CHAIN_ID.BASE]: "base",
  [CHAIN_ID.HELA]: "hela",
  [CHAIN_ID.IOTAEVM]: "iotaevm",
  [CHAIN_ID.JBC]: "jbc",
  [CHAIN_ID.EVMOS]: "evmos",
  [CHAIN_ID.CARBON]: "carbon",
  [CHAIN_ID.SMARTBCH]: "smartbch",
  [CHAIN_ID.ARTELA]: "artela",
  [CHAIN_ID.IMMUTABLE_ZKEVM]: "immutable zkevm",
  [CHAIN_ID.LOOP]: "loop",
  [CHAIN_ID.GENESYS]: "genesys",
  [CHAIN_ID.EOS_EVM]: "eos evm",
  [CHAIN_ID.MAP_PROTOCOL]: "map protocol",
  [CHAIN_ID.SAPPHIRE]: "sapphire",
  [CHAIN_ID.BITGERT]: "bitgert",
  [CHAIN_ID.FUSION]: "fusion",
  [CHAIN_ID.ZILLIQA]: "zilliqa",
  [CHAIN_ID.APECHAIN]: "apechain",
  [CHAIN_ID.EDU_CHAIN]: "edu chain",
  [CHAIN_ID.ARBITRUM]: "arbitrum",
  [CHAIN_ID.ARBITRUM_NOVA]: "arbitrum nova",
  [CHAIN_ID.CELO]: "celo",
  [CHAIN_ID.OASIS]: "oasis",
  [CHAIN_ID.ASSETCHAIN]: "assetchain",
  [CHAIN_ID.ETHERLINK]: "etherlink",
  [CHAIN_ID.AVALANCHE]: "avalanche",
  [CHAIN_ID.REI]: "rei",
  [CHAIN_ID.ZIRCUIT]: "zircuit",
  [CHAIN_ID.SOPHON]: "sophon",
  [CHAIN_ID.ETN]: "etn",
  [CHAIN_ID.SUPERPOSITION]: "superposition",
  [CHAIN_ID.REICHAIN]: "reichain",
  [CHAIN_ID.BOBA_BNB]: "boba_bnb",
  [CHAIN_ID.INK]: "ink",
  [CHAIN_ID.LINEA]: "linea",
  [CHAIN_ID.BOB]: "bob",
  [CHAIN_ID.GODWOKEN]: "godwoken",
  [CHAIN_ID.BERACHAIN]: "berachain",
  [CHAIN_ID.BLAST]: "blast",
  [CHAIN_ID.CHILIZ]: "chiliz",
  [CHAIN_ID.STRATIS]: "stratis",
  [CHAIN_ID.REAL]: "real",
  [CHAIN_ID.ODYSSEY]: "odyssey",
  [CHAIN_ID.TAIKO]: "taiko",
  [CHAIN_ID.BITLAYER]: "bitlayer",
  [CHAIN_ID.HYDRATION]: "hydration",
  [CHAIN_ID.PAREX]: "parex",
  [CHAIN_ID.POLIS]: "polis",
  [CHAIN_ID.KEKCHAIN]: "kekchain",
  [CHAIN_ID.SCROLL]: "scroll",
  [CHAIN_ID.ZERO_NETWORK]: "zero_network",
  [CHAIN_ID.ZKLINK_NOVA]: "zklink nova",
  [CHAIN_ID.VISION]: "vision",
  [CHAIN_ID.SAAKURU]: "saakuru",
  [CHAIN_ID.ZORA]: "zora",
  [CHAIN_ID.CORN]: "corn",
  [CHAIN_ID.NEON]: "neon",
  [CHAIN_ID.LUMIA]: "lumia",
  [CHAIN_ID.AURORA]: "aurora",
  [CHAIN_ID.HARMONY]: "harmony",
  [CHAIN_ID.PALM]: "palm",
  [CHAIN_ID.ZENIQ]: "zeniq",
  [CHAIN_ID.CURIO]: "curio",
  [CHAIN_ID.MODE]: "mode",
};

export function chainIcon(chain: CHAIN_ID): string | undefined {
  return chainSlugs[chain]
    ? `https://icons.llamao.fi/icons/chains/rsz_${encodeURIComponent(chainSlugs[chain])}.jpg`
    : undefined;
}

export function chainIdBySlug(slug: string): CHAIN_ID | undefined {
  return Object.entries(chainSlugs).find(([_, value]) => value === slug)?.[0] as
    | CHAIN_ID
    | undefined;
}

export function parseChainId(chain: string): CHAIN_ID | undefined {
  switch (chain) {
    case "eth":
    case "ethereum":
      return CHAIN_ID.ETHEREUM;
    case "polygon":
      return CHAIN_ID.POLYGON;
    case "bsc":
    case "binance":
    case "bnb":
      return CHAIN_ID.BINANCE;
    case "arbitrum":
      return CHAIN_ID.ARBITRUM;
    case "optimism":
      return CHAIN_ID.OPTIMISM;
    case "avalanche":
      return CHAIN_ID.AVALANCHE;
    case "base":
      return CHAIN_ID.BASE;
    case "zksync":
      return CHAIN_ID.ZKSYNC_ERA;
    case "solana":
    case "sol":
      return CHAIN_ID.SOLANA;
  }
  return undefined;
}

export const chainTxExplorer = (chainId: CHAIN_ID, txHash: string) => {
  switch (chainId) {
    case CHAIN_ID.SOLANA:
      return `https://solscan.io/tx/${txHash}`;
  }
  return undefined;
};
