import { CHAIN_ID } from "@liberfi/core";
import {
  UseHotTokensQueryParams,
  UseFinalStretchTokensQueryParams,
  UseNewTokensQueryParams,
  UseSearchTokensQueryParams,
  UseStockTokensQueryParams,
  UseSwapRouteQueryParams,
  UseTokenCandlesQueryParams,
  UseTokenHoldersQueryParams,
  UseTokensQueryParams,
  UseTokenTradesQueryParams,
  UseWalletTradesQueryParams,
  UseMigratedTokensQueryParams,
} from "./types";

export const QueryKeys = {
  hotTokens: (param: UseHotTokensQueryParams) => [
    "hotTokens",
    param.chain,
    param.duration,
    param.sortBy ?? "",
    param.sortDirection ?? "",
    param.tag ?? "",
    JSON.stringify((param.filters ?? []).sort()),
    JSON.stringify((param.launchpadPlatform ?? []).sort()),
    JSON.stringify((param.searchKeywords ?? []).sort()),
    JSON.stringify((param.excludeKeywords ?? []).sort()),
    JSON.stringify(
      (param.rangeFilters ?? []).sort((a, b) => (a.field ?? "").localeCompare(b.field ?? "")),
    ),
  ],
  newTokens: (param: UseNewTokensQueryParams) => [
    "newTokens",
    param.chain,
    param.sortBy ?? "",
    param.sortDirection ?? "",
    param.tag ?? "",
    JSON.stringify((param.filters ?? []).sort()),
    JSON.stringify((param.launchpadPlatform ?? []).sort()),
    JSON.stringify((param.searchKeywords ?? []).sort()),
    JSON.stringify((param.excludeKeywords ?? []).sort()),
    JSON.stringify(
      (param.rangeFilters ?? []).sort((a, b) => (a.field ?? "").localeCompare(b.field ?? "")),
    ),
  ],
  finalStretchTokens: (param: UseFinalStretchTokensQueryParams) => [
    "finalStretchTokens",
    param.chain,
    param.sortBy ?? "",
    param.sortDirection ?? "",
    param.tag ?? "",
    JSON.stringify((param.filters ?? []).sort()),
    JSON.stringify((param.launchpadPlatform ?? []).sort()),
    JSON.stringify((param.searchKeywords ?? []).sort()),
    JSON.stringify((param.excludeKeywords ?? []).sort()),
    JSON.stringify(
      (param.rangeFilters ?? []).sort((a, b) => (a.field ?? "").localeCompare(b.field ?? "")),
    ),
  ],
  migratedTokens: (param: UseMigratedTokensQueryParams) => [
    "migratedTokens",
    param.chain,
    param.sortBy ?? "",
    param.sortDirection ?? "",
    param.tag ?? "",
    JSON.stringify((param.filters ?? []).sort()),
    JSON.stringify((param.launchpadPlatform ?? []).sort()),
    JSON.stringify((param.searchKeywords ?? []).sort()),
    JSON.stringify((param.excludeKeywords ?? []).sort()),
    JSON.stringify(
      (param.rangeFilters ?? []).sort((a, b) => (a.field ?? "").localeCompare(b.field ?? "")),
    ),
  ],
  stockTokens: (param: UseStockTokensQueryParams) => [
    "stockTokens",
    param.chain,
    param.sortBy ?? "",
    param.sortDirection ?? "",
    param.tag ?? "",
    JSON.stringify((param.filters ?? []).sort()),
    JSON.stringify((param.launchpadPlatform ?? []).sort()),
    JSON.stringify((param.searchKeywords ?? []).sort()),
    JSON.stringify((param.excludeKeywords ?? []).sort()),
    JSON.stringify(
      (param.rangeFilters ?? []).sort((a, b) => (a.field ?? "").localeCompare(b.field ?? "")),
    ),
  ],
  searchTokens: (param: UseSearchTokensQueryParams) => [
    "searchTokens",
    JSON.stringify((param.chains ?? []).sort()),
    param.q ?? "",
    param.limit ? param.limit.toString() : "",
    param.sort ?? "",
    JSON.stringify((param.protocols ?? []).sort()),
    param.cursor ?? "",
    param.sortBy ?? "",
  ],
  swapRoute: (param: UseSwapRouteQueryParams) => [
    "swapRoute",
    param.chain,
    param.dex as string,
    param.userAddress,
    param.priorityFee ?? "",
    param.amount,
    param.swapMode as string,
    param.slippage.toString(),
    param.inputMint ?? "",
    param.outputMint ?? "",
  ],
  tokenCandles: (param: UseTokenCandlesQueryParams) => [
    "tokenCandles",
    param.chain,
    param.tokenAddress,
    param.resolution,
    param.from ? param.from.toString() : "",
    param.to ? param.to.toString() : "",
    param.limit ? param.limit.toString() : "",
  ],
  tokenHolders: (param: UseTokenHoldersQueryParams) => [
    "tokenHolders",
    param.chain,
    param.tokenAddress,
    param.cursor ?? "",
    param.limit ? param.limit.toString() : "",
  ],
  tokenMarketData: (chain: CHAIN_ID, tokenAddress: string) => [
    "tokenMarketData",
    chain,
    tokenAddress,
  ],
  token: (chain: CHAIN_ID, tokenAddress: string) => ["token", chain, tokenAddress],
  tokenSecurity: (chain: CHAIN_ID, tokenAddress: string) => ["tokenSecurity", chain, tokenAddress],
  tokens: (param: UseTokensQueryParams) => [
    "tokens",
    param.chain,
    param.tokenAddresses.sort().join(","),
    param.sortBy ?? "",
    param.sortDirection ?? "",
    JSON.stringify(param.filterBy ?? {}),
  ],
  tokenStats: (chain: CHAIN_ID, tokenAddress: string) => ["tokenStats", chain, tokenAddress],
  tokenTrades: (param: UseTokenTradesQueryParams) => [
    "tokenTrades",
    param.chain,
    param.tokenAddress,
    param.cursor ?? "",
    param.limit ? param.limit.toString() : "",
    param.direction ?? "",
  ],
  walletNetWorth: (chain: CHAIN_ID, walletAddress: string) => [
    "walletNetWorth",
    chain,
    walletAddress,
  ],
  walletPnl: (chain: CHAIN_ID, walletAddress: string) => [
    "walletPnl",
    chain,
    walletAddress,
  ],
  walletPnlDetails: (chain: CHAIN_ID, walletAddress: string) => [
    "walletPnl",
    chain,
    walletAddress,
  ],
  walletTrades: (param: UseWalletTradesQueryParams) => [
    "walletTrades",
    param.chain,
    param.walletAddress,
    param.cursor ?? "",
    param.limit ? param.limit.toString() : "",
    param.direction ?? "",
  ],
  uploadPresign: () => ["ipfs-upload-presign"],
  jobSubscription: (jobId: string) => ["jobSubscription", jobId],
};
